### ISSUE TITLE
responsive menu addition

### ISSUE THREAD

**Issue by aosipov** [ProjectCleverWeb/Semantic-UI-WordPress#11]
Hi Nick
Just wanted to share with you my responsive addition to the project.
## header

``` html

            <header class="ui page stackable grid" id="main-header-grid">
                <div class="eleven wide column header-menu">
            <!-- logo -->
            <a class="main-brand-link" title="<?php echo get_bloginfo('description'); ?>" href="<?php echo home_url(); ?>">
                <img src="<?php echo get_template_directory_uri(); ?>/images/p15-logo.svg" alt="Logo" class="main-brand" alt="pixel15">
            </a>
            <!-- /logo -->
                    <?php
                    /*
                     * A simple but effective way to display a menu as a Semantic UI menu
                     */
                    $main_menu_loc = 'main-menu';
                    if (has_nav_menu($main_menu_loc)) {
                        $main_menu = wp_nav_menu(array(
                            'theme_location'  => $main_menu_loc,
                            'container'       => 'div',
                            'menu_class'      => 'ui red inverted menu',
                            'echo'            => false,
                            'items_wrap'      => '<nav class="%2$s">%3$s</nav>',
                            'depth'           => 1,
                        ));
                        $main_menu = str_replace('menu-item ', 'menu-item item ', $main_menu);
                        $main_menu = str_replace('><a href="', ' href="', $main_menu);
                        $main_menu = str_replace("</a></li>\n<li ", "</a>\n<a ", $main_menu);
                        $main_menu = str_replace('"><li ', '"><a ', $main_menu);
                        $main_menu = str_replace("</li>\n</ul>", "</a>\n</nav>", $main_menu);
                        echo $main_menu;
                    }
                    ?>
                </div>
             <div class="five wide column header-search"><?php get_search_form() ?></div>
                <div id="nav-trigger" class="navbar-toggle"><i class="reorder icon"></i></div>
                <div class="mobile-navigation">
                    <div class="mobile-menu"></div>
                    <div class="mobile-search"><?php get_search_form() ?></div>
                </div>
            </header>


```
## css

``` css

.main-brand-link{
    float:left;
    height: 50px;
}
.ui.wide.input{
    width:100%
}
.ui.grid>.column.header-search{
    margin:7px 0;
}
.ui.grid>.column.header-menu{
    margin:0;
}
.mobile-menu .main-brand-link{
    display:none;
}
.mobile-menu .ui.vertical.menu{
    width:100%;
}
.navbar-toggle{
    font-size:30px;
    display: inline-block;
float: right;
margin-top: 10px;
}
.mobile-navigation{
    display:none;
    font-size: 1rem;
}
  .navbar-toggle {
    display: none; 
    cursor: pointer;
}
.mobile-search{
    padding: .83em .95em;
}
#main-header-grid{
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: moz-none;
    -ms-user-select: none;
    user-select: none;
}
.mobile-navigation.expanded{
    display: none;
}
/* =Media Queries
-------------------------------------------------------------- */
@media all and (max-width: 1000px) {
    .ui.grid>.column.header-search{
    display: none!important; 
    }
.ui.stackable.grid>.column.header-search{
    display:none!important;
}

  .header-menu>div  {
    display: none; 
}
  .navbar-toggle {
    display: block; 
} 
#main-header-grid .column.header-menu{
    display: inline-block!important;
}
}


```
## javascript

``` javascript

$(document).ready(function() {

    $(".mobile-menu").html($(".header-menu").html());
    $(".mobile-menu nav").addClass("vertical");

    $("#nav-trigger").click(function(){
            if ($(".mobile-navigation").hasClass("expanded")) {
                $(".mobile-navigation.expanded").removeClass("expanded").slideUp(250);
                 $(this).removeClass("open");
                $(this).children().removeClass("close");
            } else {
                $(".mobile-navigation").addClass("expanded").slideDown(250);
                $(this).addClass("open");
                $(this).children().addClass("close");
            }
        });
$( window ).resize(function() {
    if ($(".mobile-navigation").hasClass("expanded")){
    $(".mobile-navigation").removeClass("expanded").slideUp(250);
                  $("#nav-trigger").removeClass("open");
                 $("#nav-trigger").children().removeClass("close");
    }
});
});

```

Thanks:)
